# Generated by Django 4.2.3 on 2023-07-18 11:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_ID', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SKUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Packaging', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Purchase_Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.purchase_orders')),
            ],
        ),
    ]
