# Generated by Django 4.1.1 on 2023-07-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
