# Generated by Django 4.2.3 on 2023-08-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='name',
            new_name='Warehouse',
        ),
    ]
