# Generated by Django 4.2.3 on 2023-08-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_rename_name_warehouse_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='Warehouse',
            new_name='name',
        ),
    ]
