# Generated by Django 4.2.3 on 2023-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_remove_goods_received_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='purchase_ID',
            field=models.CharField(max_length=50),
        ),
    ]
