# Generated by Django 4.2.3 on 2023-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_rename_warehouse_warehouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='date',
            field=models.DateField(default='2023-08-03'),
            preserve_default=False,
        ),
    ]
