# Generated by Django 4.2.3 on 2023-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_checkin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
