# Generated by Django 4.2.3 on 2023-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0005_rename_description_checkin_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
