# Generated by Django 4.2.3 on 2023-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_checkin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='Description',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='purchase_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
