# Generated by Django 4.2.3 on 2023-08-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0007_alter_description_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='Purchase_Order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_system.purchase_order'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
