# Generated by Django 4.2.3 on 2023-08-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0008_alter_checkin_purchase_order_alter_checkin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='Purchase_Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.purchase_order'),
        ),
    ]
