# Generated by Django 4.2.3 on 2023-08-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0009_alter_checkin_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='Purchase_Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.purchase_order'),
        ),
    ]
