# Generated by Django 4.2.3 on 2023-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0010_alter_checkin_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
