# Generated by Django 4.2.3 on 2023-08-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0011_alter_checkin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='Purchase_Order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management_system.purchase_order'),
        ),
    ]
