# Generated by Django 4.2.3 on 2023-08-08 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0012_alter_checkin_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('Purchase_Order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management_system.purchase_order')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.description')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='Client',
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
        migrations.AddField(
            model_name='project_type',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.client'),
        ),
    ]
