# Generated by Django 4.2.3 on 2023-08-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0013_goods_received_owner_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_received',
            name='Project_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.project_type'),
        ),
        migrations.AddField(
            model_name='project_type',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.owner'),
        ),
        migrations.AlterUniqueTogether(
            name='goods_received',
            unique_together={('Purchase_Order', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='project_type',
            unique_together={('client', 'name')},
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project_type')),
            ],
        ),
    ]
